### ISSUE TITLE
Option when == 'newer' ?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [bealearts/grunt-periodic#1]
Hi,

I was looking at your grunt plugin and I using it to do my `npm install` and `bower install` daily. Actually I would need another option that runs these two commands only if `bower.json` or `package.json` have been changed (so, if they are newer from the last time they were checked) let's say by a `git pull`.

Is it possible to have something like this?

Thanks in advance :)

---

Proposed syntax
```js
periodic: {
 newer : {
  when: 'newer',
  files: [{
   src: [ 'bower.json', 'package.json' ]
  }],
  task: [
   'npm-install',
   'bower-install'
  ]
 }
}
```

**Comment by DavidBeale** [comment]
Hi,

I don't think it should part of the functionality of this task, but its an interesting idea for another task.

As a thought, have you considered trying to use ```grunt-newer``` for this?

**Comment by julianxhokaxhiu** [comment]
Yes I saw it but I don't have any clue on how can I combine my scenario with your plugin and/or with grunt-newer.

I was trying implementing the newer logic on your grunt task but I'm not sure if it works. I have to test it tomorrow. But meanwhile I'm open to new ideas as well :)

**Comment by DavidBeale** [comment]
Finally found some time to add this feature in v1.1.0

**Comment by julianxhokaxhiu** [comment]
Woo! Thank you!
